baseurl = "https://owenderby.com/"
languageCode = "en-US"
title = "Owen Derby"
# Enable comments by entering your Disqus shortname
disqusShortname = "owenderby"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-38535701-2"
theme = "hugo-sustain"
footnotereturnlinkcontents = "↩"
enableEmoji = true
ignoreFiles = ["LICENSE.md"]

[blackfriday]
  hrefTargetBlank = true

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Owen Derby"
  description = "My personal soap box."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  Github        = "oderby"
  Email         = "me@owenderby.com"
  LinkedIn      = "oderby"
  Twitter       = "ocderby"
  # Stackoverflow = "username"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
